version: "3" 
services:
  db:
    container_name: random_product_database
    image: "mysql:${MYSQL_VERSION}"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USER_NAME}"
      MYSQL_PASSWORD: "${DATABASE_USER_PASSWORD}"

  phpmyadmin:
    container_name: random_product_phpmyadmin
    image: "phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}"
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: "${DATABASE_USER_NAME}"
      PMA_PASSWORD: "${DATABASE_USER_PASSWORD}"
    ports:
      - "8080:80"
      
  wordpress:
    container_name: random_product_wordpress_composer
    depends_on:
      - db
    build:
      context: .
      dockerfile: wordpress.dockerfile
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "${DATABASE_USER_NAME}"
      WORDPRESS_DB_PASSWORD: "${DATABASE_USER_PASSWORD}"
      WORDPRESS_DB_NAME: "${DATABASE_NAME}"
    volumes:
      ["./plugins:/var/www/html/wp-content/plugins"]
volumes:
  mysql: {}

  
